Compression: uncompressed
Traceback (most recent call last):
  File "/home/python/.local/lib/python3.12/site-packages/onebrc/decorators/timeit.py", line 72, in _signal_handler
    raise TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/python/.local/lib/python3.12/site-packages/onebrc/12_mult_avro_duckdb.py", line 40, in <module>
    main(args.path, args.avg, args.timeout)
  File "/home/python/.local/lib/python3.12/site-packages/onebrc/12_mult_avro_duckdb.py", line 27, in main
    exec_func(_main, timeout, path)
  File "/home/python/.local/lib/python3.12/site-packages/onebrc/decorators/timeit.py", line 15, in exec_func
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/python/.local/lib/python3.12/site-packages/onebrc/12_mult_avro_duckdb.py", line 22, in _main
    res = con.execute(stmt).fetchall()
          ^^^^^^^^^^^^^^^^^
RuntimeError: Query interrupted
make: *** [Makefile:248: run-mult_avro_duckdb-1b-docker] Error 1
